// Code generated by protoc-gen-go. DO NOT EDIT.
// source: media.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MediaKey struct {
	// Media key to be used as described by:
	// https://github.com/sigalor/whatsapp-web-reveng#decryption
	MediaKey *string `protobuf:"bytes,1,opt,name=mediaKey" json:"mediaKey,omitempty"`
	// SHA-256 hash of .enc file
	FileEncSha256 *string `protobuf:"bytes,2,opt,name=fileEncSha256" json:"fileEncSha256,omitempty"`
	// This is a Unix epoch timestamp of something
	Timestamp *int64 `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	// No idea what the significance of this boolean field is
	Foo                  *bool    `protobuf:"varint,4,opt,name=foo" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaKey) Reset()         { *m = MediaKey{} }
func (m *MediaKey) String() string { return proto.CompactTextString(m) }
func (*MediaKey) ProtoMessage()    {}
func (*MediaKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_07eb54b56db72a97, []int{0}
}

func (m *MediaKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaKey.Unmarshal(m, b)
}
func (m *MediaKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaKey.Marshal(b, m, deterministic)
}
func (m *MediaKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaKey.Merge(m, src)
}
func (m *MediaKey) XXX_Size() int {
	return xxx_messageInfo_MediaKey.Size(m)
}
func (m *MediaKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaKey.DiscardUnknown(m)
}

var xxx_messageInfo_MediaKey proto.InternalMessageInfo

func (m *MediaKey) GetMediaKey() string {
	if m != nil && m.MediaKey != nil {
		return *m.MediaKey
	}
	return ""
}

func (m *MediaKey) GetFileEncSha256() string {
	if m != nil && m.FileEncSha256 != nil {
		return *m.FileEncSha256
	}
	return ""
}

func (m *MediaKey) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *MediaKey) GetFoo() bool {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return false
}

func init() {
	proto.RegisterType((*MediaKey)(nil), "main.MediaKey")
}

func init() { proto.RegisterFile("media.proto", fileDescriptor_07eb54b56db72a97) }

var fileDescriptor_07eb54b56db72a97 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x4d, 0x4d, 0xc9,
	0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xaa, 0xe1,
	0xe2, 0xf0, 0x05, 0x09, 0x7a, 0xa7, 0x56, 0x0a, 0x49, 0x71, 0x71, 0xe4, 0x42, 0xd9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x90, 0x0a, 0x17, 0x6f, 0x5a, 0x66, 0x4e, 0xaa, 0x6b,
	0x5e, 0x72, 0x70, 0x46, 0xa2, 0x91, 0xa9, 0x99, 0x04, 0x13, 0x58, 0x01, 0xaa, 0xa0, 0x90, 0x0c,
	0x17, 0x67, 0x49, 0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62, 0x6e, 0x81, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0x73, 0x10, 0x42, 0x40, 0x48, 0x80, 0x8b, 0x39, 0x2d, 0x3f, 0x5f, 0x82, 0x45, 0x81, 0x51, 0x83,
	0x23, 0x08, 0xc4, 0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x93, 0xce, 0x98, 0x91, 0x00, 0x00,
	0x00,
}
